name: Test
on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Check with linters
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3  
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:  
        python-version: "3.12" 
    - name: Check with linter 
      run: |
        pip install ruff==0.5.2
        ruff check

  test:
    name: Run smoke tests 
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3  
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:  
        python-version: "3.12" 
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests 
      run: pytest
