name: Test
on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Check with linters
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:  
        python-version: "3.12" 
    - name: Check with linter 
      run: |
        pip install ruff==0.5.2
        ruff check

  test:
    name: Run smoke tests 
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:  
        python-version: "3.12" 
    - name: Install dependencies
      run: |
        pip install poetry==1.8.3
        poetry export --without-hashes --with=dev --format=requirements.txt > requirements.txt
        pip install --no-cache-dir -r requirements.txt
    - name: Run tests 
      run: pytest
